version: 0.2

phases:
  pre_build:
    commands:
      - echo "the pre_build phase begins"
      - echo "PORT=$PORT" > server/.env
      - echo "SOCKET_PORT=$SOCKET_PORT" >> server/.env
      - echo "FRONT_END=$FRONT_END" >> server/.env
      - echo "MONGO_URL=$MONGO_URL" >> server/.env
      - echo "SECRET_KEY=$SECRET_KEY" >> server/.env
      - echo "TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID" >> server/.env
      - echo "TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN" >> server/.env
      - echo "TWILIO_VERIFY_SID=$TWILIO_VERIFY_SID" >> server/.env
      - echo "NODEMAILER_USER_EMAIL=$NODEMAILER_USER_EMAIL" >> server/.env
      - echo "NODEMAILER_PASS=$NODEMAILER_PASS" >> server/.env

  build:
    commands:
      - echo "the build phase begins"

  install:
    commands:
      - echo "the installation phase begins"

artifacts:
  files:
    - appspec.yml
    - server/.env
    - server/**/*
    - nginx/*
    - scripts/*
    - docker-compose.yml
    - Dockerfile
