#vi buildspec.yml
version: 0.2
phases:
  install:
    commands:
      - echo "the installation phase begins"

artifacts:
  files:
    - appspec.yml
    - server/**/*
    - nginx/*
    - scripts/*
    - docker-compose.yml
    - Dockerfile
