#vi buildspec.yml
version: 0.2
phases:
  install:
    commands:
      - echo "the installation phase begins"
  pre_build:
    commands:
      - echo "the prebuild phase begins"
      - cd client
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "the build phase begins"
      # - echo `pwd`
      - npm run build
      # - echo `ls -la`

  post_build:
    commands:
      - echo "Current directory: $(pwd)"
      - ls -al
      - ls -al dist/
      - cp -R dist/ ../

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - Bookat-server/**/*
    - nginx/*
    - scripts/*
    - docker-compose.yaml
    - Dockerfile
